FROM mhart/alpine-node
WORKDIR /app

COPY ./src src
COPY ./package.json package.json
COPY ./yarn.lock yarn.lock
COPY ./tsconfig.json tsconfig.json
COPY ./webpack.config.js webpack.config.js

RUN yarn install
RUN yarn build

FROM mhart/alpine-node:slim
COPY --from=0 /app /app
WORKDIR /app

COPY ./standalone.js standalone.js

CMD ["node", "standalone.js"]
