export const STATUSES = {
  latest: 'latest',
  active: 'active',
  waiting: 'waiting',
  completed: 'completed',
  failed: 'failed',
  delayed: 'delayed',
  paused: 'paused',
}

export const FIELDS = {
  [STATUSES.active]: [
    'attempts',
    'data',
    'id',
    'name',
    'opts',
    'progress',
    'timestamps',
  ],
  [STATUSES.completed]: [
    'attempts',
    'data',
    'id',
    'name',
    'opts',
    'progress',
    'timestamps',
  ],
  [STATUSES.delayed]: [
    'attempts',
    'data',
    'delay',
    'id',
    'name',
    'opts',
    'timestamps',
  ],
  [STATUSES.failed]: [
    'attempts',
    'failedReason',
    'id',
    'name',
    'progress',
    'retry',
    'timestamps',
  ],
  [STATUSES.latest]: [
    'attempts',
    'data',
    'id',
    'name',
    'opts',
    'progress',
    'timestamps',
  ],
  [STATUSES.paused]: ['attempts', 'data', 'id', 'name', 'opts', 'timestamps'],
  [STATUSES.waiting]: ['data', 'id', 'name', 'opts', 'timestamps'],
}
