name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --immutable
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true

      - name: Test
        run: yarn test
        env:
          CI: true
          REDIS_HOST: localhost
          REDIS_PORT: 6379

      - name: Release
        run: npx release-it --ci --no-increment --npm.publish --github.release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
